# -*- coding: utf-8 -*-
"""connect_mongodb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FedR5GB873KwVsJyJmteLvUF0wKsW2uw
"""

from google.colab import drive
drive.mount('/content/drive')

!python -m pip install "pymongo[srv]"

from urllib.parse import quote_plus

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

import pandas as pd
from pymongo import MongoClient

# 1. Load your CSV file
csv_file = "/content/drive/MyDrive/language_translate_project/hindi_to_multi_lang_translations.csv"
df = pd.read_csv(csv_file)

# 2. Convert DataFrame to a list of dictionaries
data = df.to_dict(orient="records")

# 3.Use the new password
username = "patilchaitra612"
password = "12345"  # exactly as set in MongoDB Atlas

uri = f"mongodb+srv://{username}:{password}@cluster1.oxcvzfp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

client = MongoClient(uri, server_api=ServerApi('1'))

try:
    client.admin.command('ping')
    print("✅ Successfully connected to MongoDB Atlas!")
except Exception as e:
    print("❌ Connection failed:", e)

# 4. Select database and collection
db = client["hindi_translation_DB"]        # Database name
collection = db["translations_collection"] # Collection name

# 5. Insert data into MongoDB
if data:  # Only insert if there's data
    collection.insert_many(data)
    print(f"✅ Inserted {len(data)} records into MongoDB Atlas.")
else:
    print("⚠️ No data found in CSV.")

# 6. Verify insertion (optional)
print(f"Total documents in collection: {collection.count_documents({})}")

import pandas as pd

# Load CSV file
csv_file = "/content/drive/MyDrive/language_translate_project/hindi_to_multi_lang_translations.csv"
df = pd.read_csv(csv_file)

df



